services:
  # Sets up how to make the source data available
  demo: {}
  tms: {}
  wmts: {}
  wms:
    # SRS sets the coordinate reference systems to make data available
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']

layers:
  # Sets up which layers you want to make available using the services above
  - name: glri_projects
    title: GLRI Projects
    sources: [glri_projects_cache]
    
  - name: osm_bright
    title: OpenStreetMap Bright Layer
    sources: [osm_bright_cache]

  - name: luftbild
    title: Aktuelle Luftbild
    sources: [luftbild_cache]

caches:
  # Sets up how to cache the source data
  glri_projects_cache:
    grids: [osm_bright_grid]
    sources: [glri_projects_source]

  luftbild_cache:
    grids: [osm_bright_grid]
    sources: [luftbild_source]
    format: image/png

  osm_bright_cache:
    grids: [osm_bright_grid]
    sources: [osm_bright_source]
    format: image/png


sources:
  glri_projects_source:
    type: wms
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']
    req:
      url: http://crystalball.timetochange.today/geoserver/workspace1/ows
      layers: glri_projects
      transparent: true

  luftbild_source:
    type: wms
    supported_formats: [png, jpeg]
    supported_srs: ['EPSG:3857', 'EPSG:4326', 'EPSG:25832']
    req:
      url: https://geoserver.stuttgart.de/geoserver/Base/wms
      layers: Base:A62_Luftbild_aktuell_EPSG25832
      transparent: true

  osm_bright_source:
    type: tile
    url: https://geo.timetochange.today/geoserver/gwc/service/tms/1.0.0/osm:osm_bright@EPSG:900913@png/%(z)s/%(x)s/%(y)s.png
    grid: osm_bright_grid_reverse

grids:
  osm_bright_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw

  osm_bright_grid_reverse:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: sw

globals:

  cache:
    # Where to store the cached images
    base_dir: './cache_data'
    # Where to store lockfiles
    lock_dir: './cache_data/locks'

  image:
    # Image/transformation options
    resampling_method: bilinear
    jpeg_quality: 90

